### PR TITLE
Support for 1440p resolution

### PR DESCRIPTION
**Pull request by Tokahiro**

### CODE REVIEW

**Comment by qwerty2k** [comment]
I was just in the middle of doing this, so good work on beating me to it. Have you found it to be reliable? I have set the settings pretty much identical to this patch yet my resolution keeps jumping between 1440p and 4k on my 5k iMac and won't stick to 1440p. Have you had the same issue?

**Comment by Tokahiro** [comment]
On my machine (Macbook Pro 15 2017) constant 1440p. That could be because I only have WQHD screen and my Macbook can't handle 4k with VP9 Codec (thanks Google and Apple)
image

**Comment by qwerty2k** [comment]
interesting, I just got your patches and merged them in, on my late 2015 5k iMac window.screen shows the correct dimensions etc but im still getting served 4k :(. My cpu can't handle 4k so was hoping 1440p would be a good balance between quality and performance.

will do some more investigating. Tried in Assassins Creed Odyssey and Destiny 2.

**Comment by Mafrans** [comment]
Seems to me like it should work for most people, waiting to merge in case there are any issues we haven't found yet.

**Comment by Mafrans** [comment]
Seeing as nobody has commented on it not working, I'll merge this.

**Pull request merged**
