### PR TITLE
GitHub Actions

### PR DESCRIPTION
**Pull request by nihaals**
This adds GitHub Actions.

On a commit or PR, it will build the dist.zip.

On a tag push, it will build the dist.zip, create a release, upload the dist.zip to it and upload it to the Chrome WebStore.

I've made the setup the exact same as the current one, for example, the release asset is named the same. The release created is a `draft`, allowing you to edit it, add a change log then publish it when it is ready. While in the draft state, no one else can see it.

This also removes the need for the out of date dist folder, as every commit will have it attached ready in the form to be added to the browser.

The dist currently only includes the needed files as users can still inspect the source by looking here, and due to your use of CI, it will be more trusted compared to before where there is a possibility of the author manipulating it before uploading. This also shrinks the dist zip.

If you haven't used GitHub Actions before, it's completely free and artefacts are stored for 90 days. You can see what getting the artefact is like by looking at [my fork](https://github.com/nihaals/StadiaPlus/actions). If you click on a run, it is shown under `Artifacts`.

It also checks if you forgot to update the manifest before pushing the tag (this can be changed where the manifest is updated during CI so it is always in sync, and in the file it might be something like `{{VERSION}}`, which seems to be where modern packages are going, but I wanted to keep this as close to your existing workflow as possible).

The WebStore upload might be too much, I can remove it if it makes more sense.

[How to get Chrome WebStore credentials](https://github.com/DrewML/chrome-webstore-upload/blob/master/How%20to%20generate%20Google%20API%20keys.md)

### CODE REVIEW

**Comment by Mafrans** [comment]
I would prefer if the actions didn't automatically publish to the web store or even build prod builds at all. Until I consider there to be enough content for an update I want to limit Stadia+ to dev builds only. If the extension automatically publishes anything on the web store or in the github release section there might be breaking errors that can cause people's Stadia clients to, at worst, stop functioning completely.

**Comment by nihaals** [comment]
So make it only build the artefacts and use `npm run build:dev`? Since the releases are only controlled by you and when you push a tag, it shouldn’t be any different to the way it is now, since you would still need to bump the version and create a tag, which you would do after it’s been tested/verified

**Comment by Mafrans** [comment]
Will leave this open for now, as I don't see a definite reason to use actions at the moment. Still a very useful idea for the future, though.

**Comment by nihaals** [comment]
I just thought of another possible advantage: nightly builds. It could be nice to be able to give users the option to update to the latest commit automatically (of course if they choose, they would be aware of the stability differences). Could help beta test new things and just help users get the new exciting updates sooner (for example I was looking forward to 1440p as 4k does not run very well for me and being able to opt in to a buggy version would have been fine)

**Comment by Mafrans** [comment]
Will take that into account

**Comment by dotLou** [comment]
Something that might be useful to consider would be the new support for [manually triggering workflows](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) - this could give you the ease of use of actions with the flexibility to only publish to the store when you really want to :)

**Comment by nihaals** [comment]
Thanks for pointing that out, completely missed that blog post but looks useful, especially for this

**Pull request closed without merging**
